name: markdownr
description: Convert a URL to Markdown and share it to your favorite app.
publish_to: "none"
version: 1.6.1+13

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  html2md: ^1.3.2
  intl: ^0.20.2
  share_plus: ^12.0.1
  receive_sharing_intent: ^1.8.1
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.4
  flutter_charset_detector: ^5.0.0
  charset_converter: ^2.3.0
  flutter_markdown_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.6.3
  build_runner: ^2.12.2
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true
